### ISSUE TITLE
Linkedin URL 404 ERROR

### ISSUE THREAD

**Issue by 1chooo** [onepiece010938/onepiece010938#1]
Hi Raymond,

我是 Hugo 我從鐵人賽 --- **Golang LineBot X GoogleDrive：LINE有各種限制!? 那就丟上Drive吧!** 找到您，本來想透過 Linkedin 與您聯絡，不過發現主頁 Linkedin 網址沒辦法 reach out，因此才透過 Issue 的方式前來聯繫！非常抱歉造成你的困擾，希望可以照著你的鐵人賽也實作出一個 GoLang 與 AWS 結合的 LINE BOT！

BR,
@1chooo

**Comment by onepiece010938** [comment]
HI, Hugo 
我有加你Linkedin了，謝謝你的發現，link我也update了，歡迎跟我聯繫。
